### ISSUE TITLE
Fix Minecraft Text Parser

### ISSUE THREAD

**Issue by haloflooder** [ClubObsidian/DynamicGuiCreator#2]
Need to properly implement a way to escape &'s in the current javascript code.

Currently, the parser shows "& & &f &f" when "& && &&& &&f& &&&f&" goes through the parser. It should look like "& && &&& &f& &f&"

Also, the text parser in minecraft is a bit weird.

![](https://i.imgur.com/HwXKEgB.png)

I thought &&&&f would show &&f in the chat but nope.

**Comment by virustotalop** [comment]
Implementation in bukkit
![bukkit implementation](https://i.imgur.com/YWm8NCp.png)

**Comment by haloflooder** [comment]
Found out essentials takes over the chat/msg chat parser. They use regex. 

Fixed the parser to so it properly parses the minecraft text.
![](https://i.imgur.com/M8DAzd4.png)
